import { IMAGES } from "./images";

export const SKILLS = [
  {
    name: "Next.js",
    href: "https://nextjs.org/",
    image: "https://www.svgrepo.com/show/368858/nextjs.svg",
    showAsExpertise: true,
  },
  {
    name: "React.js",
    href: "https://react.dev/",
    image: "https://www.svgrepo.com/show/374032/reactjs.svg",
    showAsExpertise: true,
  },
  {
    name: "React Native",
    href: "https://reactnative.dev/",
    image: "https://www.svgrepo.com/show/374035/reactts.svg",
    showAsExpertise: true,
  },
  {
    name: "Expo",
    href: "https://expo.dev/",
    image: "https://www.svgrepo.com/show/341805/expo.svg",
    showAsExpertise: true,
  },
  {
    name: "Express.js",
    href: "https://expressjs.com/",
    image: "https://www.svgrepo.com/show/330398/express.svg",
    showAsExpertise: true,
  },
  {
    name: "Nest.js",
    href: "https://nestjs.com/",
    image: "https://www.svgrepo.com/show/373872/nestjs.svg",
    showAsExpertise: true,
  },
  {
    name: "MongoDb",
    href: "https://www.mongodb.com/",
    image: "https://www.svgrepo.com/show/373845/mongo.svg",
    showAsExpertise: true,
  },
  {
    name: "Prisma",
    href: "https://www.prisma.io/",
    image: "https://www.svgrepo.com/show/354210/prisma.svg",
    showAsExpertise: true,
  },
  {
    name: "Redis",
    href: "https://redis.io/",
    image: "https://www.svgrepo.com/show/354272/redis.svg",
    showAsExpertise: false,
  },
  {
    name: "Redux.js",
    href: "https://react-redux.js.org/",
    image: "https://www.svgrepo.com/show/452093/redux.svg",
    showAsExpertise: true,
  },
  {
    name: "Firebase",
    href: "https://firebase.google.com/",
    image: "https://www.svgrepo.com/show/373595/firebase.svg",
    showAsExpertise: false,
  },
  {
    image: "https://www.svgrepo.com/show/333088/framer.svg",
    name: "Framer Motion (Motion)",
    showAsExpertise: false,
    href: "https://motion.dev/",
  },
  {
    image: IMAGES.icons["threejs"],
    name: "Three.js",
    showAsExpertise: false,
    href: "https://threejs.org/",
  },
  {
    image: "https://avatars.githubusercontent.com/u/96090470?s=200&v=4",
    name: "Plasmo",
    showAsExpertise: false,
    href: "https://www.plasmo.com/",
  },
  {
    name: "Typescript",
    href: "https://www.typescriptlang.org/",
    image: "https://www.svgrepo.com/show/354478/typescript-icon.svg",
    showAsExpertise: true,
  },
  {
    image: "https://docs.pmnd.rs/zustand.ico",
    name: "Zustand",
    showAsExpertise: true,
    href: "https://docs.pmnd.rs/zustand/getting-started/introduction",
  },
  {
    image: IMAGES.icons["react-query"],
    name: "React Query",
    showAsExpertise: true,
    href: "https://tanstack.com/query/v3/",
  },
  {
    image: IMAGES.icons["react-hook-form"],
    name: "React Hook Form",
    showAsExpertise: true,
    href: "https://react-hook-form.com/",
  },
  {
    image: IMAGES.icons.zod,
    name: "Zod",
    showAsExpertise: true,
    href: "https://zod.dev/",
  },
  {
    image: IMAGES.icons.vitest,
    name: "Vitest",
    showAsExpertise: false,
    href: "https://vitest.dev/",
  },
  {
    name: "Node.js",
    href: "https://nodejs.org/en",
    image: "https://www.svgrepo.com/show/354119/nodejs-icon.svg",
    showAsExpertise: false,
  },
  {
    name: "Javascript",
    href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    image: "https://www.svgrepo.com/show/353925/javascript.svg",
    showAsExpertise: false,
  },
  {
    name: "Git",
    image: "https://www.svgrepo.com/show/452210/git.svg",
    showAsExpertise: false,
    href: "https://git-scm.com/",
  },
  {
    image: "https://www.svgrepo.com/show/512317/github-142.svg",
    name: "Github",
    showAsExpertise: false,
    href: "https://github.com/",
  },
  {
    image: "https://www.svgrepo.com/show/373827/markdown.svg",
    name: "Markdown",
    showAsExpertise: false,
    href: "https://www.markdownguide.org/",
  },
  {
    image: "https://www.svgrepo.com/show/373768/light-mdx.svg",
    name: "Mdx",
    showAsExpertise: false,
    href: "https://mdxjs.com/",
  },
  {
    name: "TailwindCSS",
    href: "https://tailwindcss.com/",
    image: "https://www.svgrepo.com/show/374118/tailwind.svg",
    showAsExpertise: true,
  },
  {
    name: "SASS/SCSS",
    href: "https://sass-lang.com/",
    image: "https://www.svgrepo.com/show/374067/scss2.svg",
    showAsExpertise: false,
  },
  {
    name: "CSS",
    href: "https://developer.mozilla.org/en-US/docs/Web/CSS",
    image: "https://www.svgrepo.com/show/452185/css-3.svg",
    showAsExpertise: false,
  },
  {
    name: "HTML",
    href: "https://developer.mozilla.org/en-US/docs/Web/HTML",
    image: "https://www.svgrepo.com/show/452228/html-5.svg",
    showAsExpertise: false,
  },
  {
    name: "C++",
    image: "https://www.svgrepo.com/show/452183/cpp.svg",
    href: "https://cplusplus.com/",
    showAsExpertise: false,
  },
  {
    name: "C Language",
    image: "https://www.svgrepo.com/show/373482/c.svg",
    href: "https://en.wikipedia.org/wiki/C_(programming_language)",
    showAsExpertise: false,
  },
  {
    name: "Bash Scripting",
    image: "https://www.svgrepo.com/show/353478/bash-icon.svg",
    href: "https://devdocs.io/bash/",
    showAsExpertise: false,
  },
] as const;

export type SkillNames = (typeof SKILLS)[number]["name"];
